server:
  servlet:
    context-path: /api-producao
spring:
  application:
    name: Api Producao
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${MESSAGE_BROKER_DOMAIN}
    password: ${MESSAGE_BROKER_PASS}
    port: ${MESSAGE_BROKER_PORT}
    username: ${MESSAGE_BROKER_USER}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
queue1:
  name: pedido-recebido
    
 