name: kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v3
      env:
        AWS_DEFAULT_REGION:
        AWS_REGION:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
        AWS_SESSION_TOKEN:
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: ${{ vars.AWS_REGION }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-skip-session-tagging: true

    - run: git clone https://github.com/grunbruno/tech-fase4-tf-k8s.git

    - name: Show AWS CLI Configuration
      run: aws configure list
           
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3
 
    - name: Terraform Init
      run: terraform -chdir=tech-fase4-tf-k8s/infra init 

    - name: Terraform Validate
      run: terraform -chdir=tech-fase4-tf-k8s/infra validate

    - name: LS
      run: ls

    - name: Terraform Apply
      run: terraform -chdir=tech-fase4-tf-k8s/infra apply -auto-approve 
  
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3
      
    - run: aws sts get-caller-identity
    
    - run: aws eks update-kubeconfig --region us-east-1 --name ${{ vars.AWS_EKS_CLUSTER_NAME }} 

    - run: cat ~/.kube/config
    
    - run: kubectl get svc

    - name: Criando configMap da APP
      run: kubectl apply -f tech-fase4-tf-k8s/k8s-app/app-configmap.yaml

    - name: Criando Deployment da APP
      run: kubectl apply -f tech-fase4-tf-k8s/k8s-app/app-deployment.yaml

    - name: Criando SVC da APP
      run: kubectl apply -f tech-fase4-tf-k8s/k8s-app/app-svc.yaml
      
    - name: Alterando a imagem da APP
      run: kubectl set image deployment/tech-challenge-java-app-deployment tech-challenge-java-pod=${{ vars.DOCKER_IMAGE_NAME }}:${{ vars.DOCKER_IMAGE_VERSION }}
